### ISSUE TITLE
Default picture not shown when enumeration value isn't found

### ISSUE THREAD

**Issue by melvingrootenboers** [ChrisdeG/EnumToggle#3]
Selected enum key: NOTEXISTING
![image](https://cloud.githubusercontent.com/assets/10810429/11775545/0ea8fe8a-a240-11e5-9f6b-6996d14f506c.png)

Expected image: Systems.Images.Cancel
![image](https://cloud.githubusercontent.com/assets/10810429/11775578/6d4fba32-a240-11e5-8340-72f3efe2068b.png)

Actual image: TestSuite.Images.Maggie_Simpson_icon
![image](https://cloud.githubusercontent.com/assets/10810429/11775588/7cf4f056-a240-11e5-97bc-6f665f4e661c.png)

The default picture is expected, because the enumeration value NOTEXISTING, doesn't exists in the Level enumeration.

**Comment by ChrisdeG** [comment]
Beste Melvin,

Je hebt gelijk. Maar eigenlijk moet ik ook een foutmelding geven: niet
bestaande enum_key: waarde

Met vriendelijke groet,

[image: FlowFabric] http://www.flowfabric.com/

Chris de Gelder

Business Consultant

cdgelder@flowfabric.com

+31(0)6 - 461 39 865

_Van:_ Melvin Grootenboers [mailto:notifications@github.com]
_Verzonden:_ Monday, December 14, 2015 8:58 AM
_Aan:_ ChrisdeG/EnumToggle
_Onderwerp:_ [EnumToggle] Default picture not shown when enumeration value
isn't found (#3)

Selected enum key: NOTEXISTING
[image: Afbeelding verwijderd door afzender. image]
https://camo.githubusercontent.com/165774f73a27e19967cdf8483ef64ef184b83b24/68747470733a2f2f636c6f756467697468756275736572636f6e74656e74636f6d2f6173736574732f31303831303432392f31313737353534352f30656138666538612d613234302d313165352d396636622d363939366431346635303663706e67

Expected image: SystemsImagesCancel
[image: Afbeelding verwijderd door afzender. image]
https://camo.githubusercontent.com/71b761ec1d03de927bd73ec148c97f893148b322/68747470733a2f2f636c6f756467697468756275736572636f6e74656e74636f6d2f6173736574732f31303831303432392f31313737353537382f36643466626133322d613234302d313165352d383334302d373266336566653230363862706e67

Actual image: TestSuiteImagesMaggie_Simpson_icon
[image: Afbeelding verwijderd door afzender. image]
https://camo.githubusercontent.com/78be776f468189c1fa9104490953dbde74518996/68747470733a2f2f636c6f756467697468756275736572636f6e74656e74636f6d2f6173736574732f31303831303432392f31313737353538382f37636634663035362d613234302d313165352d393762632d366636363566346536363163706e67

The default picture is expected, because the enumeration value NOTEXISTING,
doesn't exists in the Level enumeration

—
Reply to this email directly or view it on GitHub
https://github.com/ChrisdeG/EnumToggle/issues/3.[image: Afbeelding
verwijderd door afzender.]

**Comment by ChrisdeG** [comment]
This one is fixed
